set(__QT_DEPLOY_TARGET_inputs_FILE C:/Users/Samir/Desktop/Temp A.Abdelrazik/projects/ConApps/game_emulator/build_qt/inputs/libinputs.a)
set(__QT_DEPLOY_TARGET_inputs_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_viewer_FILE C:/Users/Samir/Desktop/Temp A.Abdelrazik/projects/ConApps/game_emulator/build_qt/viewer/libviewer.a)
set(__QT_DEPLOY_TARGET_viewer_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_games_FILE C:/Users/Samir/Desktop/Temp A.Abdelrazik/projects/ConApps/game_emulator/build_qt/games/libgames.a)
set(__QT_DEPLOY_TARGET_games_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_controller_FILE C:/Users/Samir/Desktop/Temp A.Abdelrazik/projects/ConApps/game_emulator/build_qt/controller/libcontroller.a)
set(__QT_DEPLOY_TARGET_controller_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_game_emulator_FILE C:/Users/Samir/Desktop/Temp A.Abdelrazik/projects/ConApps/game_emulator/build_qt/game_emulator.exe)
set(__QT_DEPLOY_TARGET_game_emulator_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_game_emulator_RUNTIME_DLLS C:/msys64/ucrt64/bin/Qt6Quick.dll;C:/msys64/ucrt64/bin/Qt6OpenGL.dll;C:/msys64/ucrt64/bin/Qt6Gui.dll;C:/msys64/ucrt64/bin/Qt6QmlMeta.dll;C:/msys64/ucrt64/bin/Qt6QmlModels.dll;C:/msys64/ucrt64/bin/Qt6QmlWorkerScript.dll;C:/msys64/ucrt64/bin/Qt6Qml.dll;C:/msys64/ucrt64/bin/Qt6Network.dll;C:/msys64/ucrt64/bin/Qt6Core.dll)
